### ISSUE TITLE
Module build failed (from ./node_modules/eslint-loader/index.js)

### ISSUE THREAD

**Issue by dakshshah96** [vuejs/eslint-config-standard#1]
I just updated all the dependencies for my project created with Vue CLI. The build is successful after updating all dependencies except one: `@vue/eslint-config-standard`. I'm updating from `v4.0.0` to `v5.0.0`. The error stack looks like this:

```
 ERROR  Failed to compile with 1 errors                              

 error  in ./src/main.js

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'import' declared in 'package.json » @vue/eslint-config-standard » /Users/dakshshah/Documents/fakePath/node_modules/eslint-config-standard/index.js': Cannot find module 'eslint-plugin-import'
Require stack:
- /Users/dakshshah/Documents/fakePath/__placeholder__.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Object.resolve (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/shared/relative-module-resolver.js:44:50)
    at ConfigArrayFactory._loadPlugin (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:957:39)
    at names.reduce (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:846:33)
    at Array.reduce (<anonymous>)
    at ConfigArrayFactory._loadPlugins (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:842:22)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:665:32)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:594:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/dakshshah/Documents/fakePath/node_modules/eslint/lib/cli-engine/config-array-factory.js:658:25)

 @ multi (webpack)-dev-server/client?https://192.168.1.210:8083/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by sodatea** [comment]
It's a new major release so it contains breaking changes.

See the [Release Note](https://github.com/vuejs/eslint-config-standard/releases/edit/v5.0.0):
> - `eslint-plugin-import`, `eslint-plugin-node`, `eslint-plugin-promise`, `eslint-plugin-standard` are now `peerDependencies`, to better conform to [the plugin loading mechanism of eslint](https://github.com/eslint/eslint/issues/3458)

And the reasoning behind this change: https://github.com/vuejs/eslint-config-standard/commit/75966d893d9dfa4359062896ade55545a673ffe7#commitcomment-36004406

**Comment by dakshshah96** [comment]
Sorry for the trouble and thanks for taking the time out to explain 😄
